# .streamlit/secrets.toml
[supabase]
url = "https://lfvimyjlbckcvnuponvt.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmdmlteWpsYmNrY3ZudXBvbnZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4NTExMzYsImV4cCI6MjA3ODQyNzEzNn0.stnX342ED3dt2lL5wtIcZ5ZnoXI2SYvLBzt851723J0"
db_url = "postgresql://postgres:EraTaBit201@db.lfvimyjlbckcvnuponvt.supabase.co:5432/postgres"